export const SET_TOKENS = 'AUTH/SET_TOKENS';

export const LOGIN = 'AUTH/LOGIN';
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'AUTH/LOGIN_FAIL';
export const LOGOUT = 'AUTH/LOGOUT';

export const REGISTER = 'AUTH/REGISTER';
export const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS';
export const REGISTER_FAIL = 'AUTH/REGISTER_FAIL';

export const VERIFY_EMAIL = 'AUTH/VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESS = 'AUTH/VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'AUTH/VERIFY_EMAIL_FAIL';

export const RETRY_VERIFY_EMAIL = 'AUTH/RETRY_VERIFY_EMAIL';
export const RETRY_VERIFY_EMAIL_SUCCESS = 'AUTH/RETRY_VERIFY_EMAIL_SUCCESS';
export const RETRY_VERIFY_EMAIL_FAIL = 'AUTH/RETRY_VERIFY_EMAIL_FAIL';

export const FORGOT_PASSWORD = 'AUTH/FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'AUTH/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'AUTH/FORGOT_PASSWORD_FAIL';

export const RESET_PASSWORD = 'AUTH/RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'AUTH/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'AUTH/RESET_PASSWORD_FAIL';
