
// Auth types
export const SET_TOKENS = 'AUTH/SET_TOKENS';

export const LOGIN = 'AUTH/LOGIN';
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'AUTH/LOGIN_FAIL';
export const LOGOUT = 'AUTH/LOGOUT';

export const REGISTER = 'AUTH/REGISTER';
export const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS';
export const REGISTER_FAIL = 'AUTH/REGISTER_FAIL';

export const VERIFY_EMAIL = 'AUTH/VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESS = 'AUTH/VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'AUTH/VERIFY_EMAIL_FAIL';

export const RETRY_VERIFY_EMAIL = 'AUTH/RETRY_VERIFY_EMAIL';
export const RETRY_VERIFY_EMAIL_SUCCESS = 'AUTH/RETRY_VERIFY_EMAIL_SUCCESS';
export const RETRY_VERIFY_EMAIL_FAIL = 'AUTH/RETRY_VERIFY_EMAIL_FAIL';

export const FORGOT_PASSWORD = 'AUTH/FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'AUTH/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'AUTH/FORGOT_PASSWORD_FAIL';

export const RESET_PASSWORD = 'AUTH/RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'AUTH/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'AUTH/RESET_PASSWORD_FAIL';

// Standards types
export const CREATE_STANDARD_TYPE = 'STANDARDS/CREATE_STANDARD_TYPE';

export const READ_STANDARDS = 'STANDARDS/READ_STANDARDS';
export const READ_STANDARDS_SUCCESS = 'STANDARDS/READ_STANDARDS_SUCCESS';
export const READ_STANDARDS_FAIL = 'STANDARDS/READ_STANDARDS_FAIL';

export const CREATE_STANDARD = 'STANDARDS/CREATE_STANDARD';
export const CREATE_STANDARD_SUCCESS = 'STANDARDS/CREATE_STANDARD_SUCCESS';
export const CREATE_STANDARD_FAIL = 'STANDARDS/CREATE_STANDARD_FAIL';

export const UPDATE_STANDARD = 'STANDARDS/UPDATE_STANDARD';
export const UPDATE_STANDARD_SUCCESS = 'STANDARDS/UPDATE_STANDARD_SUCCESS';
export const UPDATE_STANDARD_FAIL = 'STANDARDS/UPDATE_STANDARD_FAIL';

export const DELETE_STANDARD = 'STANDARDS/DELETE_STANDARD';
export const DELETE_STANDARD_SUCCESS = 'STANDARDS/DELETE_STANDARD_SUCCESS';
export const DELETE_STANDARD_FAIL = 'STANDARDS/DELETE_STANDARD_FAIL';

export const SELECT_MOMENT = 'STANDARDS/SELECT_MOMENT';
