export const SET_TOKENS = 'AUTH/SET_TOKENS';

export const LOGIN = 'AUTH/LOGIN';
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'AUTH/LOGIN_FAIL';
export const LOGOUT = 'AUTH/LOGOUT';

export const REGISTER = 'AUTH/REGISTER';
export const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS';
export const REGISTER_FAIL = 'AUTH/REGISTER_FAIL';

export const VERIFY_EMAIL = 'AUTH/VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESS = 'AUTH/VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'AUTH/VERIFY_EMAIL_FAIL';

export const RETRY_VERIFY_EMAIL = 'AUTH/RETRY_VERIFY_EMAIL';
export const RETRY_VERIFY_EMAIL_SUCCESS = 'AUTH/RETRY_VERIFY_EMAIL_SUCCESS';
export const RETRY_VERIFY_EMAIL_FAIL = 'AUTH/RETRY_VERIFY_EMAIL_FAIL';
