version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - server.env
    links:
      - db
    depends_on:
      - db

  db:
    image: "postgres:10"
    ports:
      - "5432:5432"
    env_file:
      - db.env
