"""empty message

Revision ID: 7fbc8e37d1c0
Revises: b59d42287ced
Create Date: 2020-04-25 14:11:56.128296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import utils


# revision identifiers, used by Alembic.
revision = '7fbc8e37d1c0'
down_revision = 'b59d42287ced'
branch_labels = None
depends_on = None

active = 'active'
email_is_not_verified = 'email_is_not_verified'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_status = postgresql.ENUM(active, email_is_not_verified, name='user_status')
    user_status.create(op.get_bind())

    op.add_column('user', sa.Column('public_id', utils.sa_guid.guid.GUID(), nullable=False, server_default=sa.text("uuid_generate_v4()")))
    op.alter_column('user', 'public_id', server_default=None)
    op.add_column('user', sa.Column('status', sa.Enum(active, email_is_not_verified, name='user_status'), nullable=False, server_default=email_is_not_verified))
    op.alter_column('user', 'status', server_default=None)
    op.create_unique_constraint(None, 'user', ['public_id'])

    op.drop_column('user', 'surname')
    op.drop_column('user', 'patronymic')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    user_status = postgresql.ENUM(active, email_is_not_verified, name='user_status')
    user_status.drop(op.get_bind())
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###
