"""The user table is expanded with name, surname, group, club columns

Revision ID: 9a5d16f75878
Revises: 7fbc8e37d1c0
Create Date: 2020-06-17 11:09:58.073041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a5d16f75878'
down_revision = '7fbc8e37d1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('club', sa.String(length=100), nullable=False, server_default="Anonymous"))
    op.add_column('user', sa.Column('group', sa.String(length=100), nullable=False, server_default="Anonymous"))
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=False, server_default="Anonymous"))
    op.add_column('user', sa.Column('surname', sa.String(length=100), nullable=False, server_default="Anonymous"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    op.drop_column('user', 'group')
    op.drop_column('user', 'club')
    # ### end Alembic commands ###
