"""Standards table

Revision ID: 9aa04954e7d0
Revises: 9a5d16f75878
Create Date: 2020-06-17 13:31:19.596277

"""
from alembic import op
import sqlalchemy as sa
import utils


# revision identifiers, used by Alembic.
revision = '9aa04954e7d0'
down_revision = '9a5d16f75878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', utils.sa_guid.guid.GUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standard')
    # ### end Alembic commands ###
